#ifndef SALARYMANAGEMENTSYSTEM_PRINT_NUMBER_DIAMOND_H
#define SALARYMANAGEMENTSYSTEM_PRINT_NUMBER_DIAMOND_H

// Êý×ÖÀâÐÎ
void print_number_diamond();

#endif //SALARYMANAGEMENTSYSTEM_PRINT_NUMBER_DIAMOND_H